MathSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("problems.urls")),
    path("admin/", admin.site.urls),
]

problems/urls.py
from django.urls import path

from . import views

app_name = "problems"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:problem_id>/answer", views.answer, name="answer"),
    path("correct", views.correct, name="correct"),
    path("incorrect", views.incorrect, name="incorrect"),
]

problems/models.py
from django.db import models

class Problem(models.Model):
    question = models.CharField(max_length=200)
    answer = models.IntegerField()
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.question
    
    def problem_type(self):
        return self.type
    
    def check_answer(self, answer):
        return answer == self.answer

problems/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from random import choice

from .models import Problem

def index(request):
    template = loader.get_template("problems/index.html")
    context = {"problem": choice(Problem.objects.all())}
    return HttpResponse(template.render(context, request))

def correct(request):
    template = loader.get_template("problems/correct.html")
    return HttpResponse(template.render({}, request))

def incorrect(request):
    template = loader.get_template("problems/incorrect.html")
    return HttpResponse(template.render({}, request))

def answer(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)
    try:
        answer = int(request.POST["answer"])
    except KeyError:
        # Redisplay the problem.
        return render(
            request,
            "problems/index.html",
            {
                "problem": problem,
                "error_message": "You didn't enter an answer.",
            },
        )
    else:
        if problem.check_answer(answer):
            return HttpResponseRedirect(reverse("problems:correct"))
        else:
            return HttpResponseRedirect(reverse("problems:incorrect"))

problems/templates/problems/correct.html
<html>
    <body>
        <p>Correct!</p>
    </body>
</html>

problems/templates/problems/incorrect.html
<html>
    <body>
        <p>Sorry, that was incorrect.</p>
    </body>
</html>

problems/templates/problems/index.html
<html>
    <body>
        <p>{{ problem }}</p>
        <form action="{% url 'problems:answer' problem.id %}" method="post">
            {% csrf_token %} 
            <label for="answer">Answer:</label><br>
            <input type="text" id="answer" name="answer"><br>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>